import { cookies } from "next/headers";
import { redirect } from "next/navigation";
import PageHome from "./Home";
import fetchData from "@/utils/fetchData";


export const metadata = {
  title: "Locasys",
  description: "Generated by create next app",
};

export default async function Home() {
    const cookieStore = cookies()
    const token = (await cookieStore).get('token')?.value
   
   
    if (!token) {
        redirect('/login')   
    }

    const branch = await fetchData(`http://${process.env.NEXT_PUBLIC_LOCALHOST}:3001/findAllBranch`, token)
    const dataEquipments = await fetchData(`http://${process.env.NEXT_PUBLIC_LOCALHOST}:3001/findAllEquipment`, token)


    if(branch.message) {
        redirect('/login')
    }

    return (
        <PageHome dataEquipments={dataEquipments}></PageHome>
       
    )
}